### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/network-config-manager#1]
Stream is opened
https://github.com/vmware/network-config-manager/blob/df2980b9349928fd0e22dac547f05026be5555d6/src/share/file-util.c#L82
Opened file never closed
https://github.com/vmware/network-config-manager/blob/df2980b9349928fd0e22dac547f05026be5555d6/src/share/file-util.c#L96

**Comment by ssahani** [comment]
`_cleanup_fclose_` automatically does. This tool is not able to figure out
