### ISSUE TITLE
add-route did not add CIDR  [0.5.2]

### ISSUE THREAD

**Issue by ufoonline** [vmware/network-config-manager#145]
### Describe the bug

OS: PhotonOS 4.0
Network-config-manager: v0.5.2 (0.5.2-1.ph4.x86_64)

Using 'add-route' command the CIDR part will be ignored.

### Reproduction steps

root@photonOS [ ~ ]# nmctl add-route eth0 gw 10.1.2.2 dest 10.5.5.0/24
root@photonOS [ ~ ]# ip r
default via 172.17.63.1 dev eth2 proto static
10.1.2.0/24 dev eth0 proto kernel scope link src 10.1.2.3
10.5.5.0 via 10.1.2.2 dev eth0 proto static
172.17.63.0/24 dev eth2 proto kernel scope link src 172.17.63.40
root@photonOS [ ~ ]#

### Expected behavior

In /etc/systemd/network/10-eth0.network we should found:
[Route]
Gateway=10.1.2.2
Destination=10.5.5.0/24

Executing 'ip r' we should have:
10.5.5.0/24 via 10.1.2.2 dev eth0 proto static

### Additional context

/etc/systemd/network/10-eth0.network content:
[Match]
Name=eth0

[Network]

[Address]
Address=10.1.2.3/24

[Route]
Gateway=10.1.2.2
Destination=10.5.5.0

**Comment by ssahani** [comment]
Please test with https://github.com/vmware/network-config-manager/pull/146

**Comment by ufoonline** [comment]
Hello, 
it fixed that issue. but maybe I found another one 'add-default-gateway' did not add the gateway under 'Address' but under 'Route'. That cause when you add a route on same interface where you have a default gateway, you will loose the defaul gateway.

Regards
