### ISSUE TITLE
add-default-gateway write 'Gateway' tag inside Route section instead of 'Network' section

### ISSUE THREAD

**Issue by ufoonline** [vmware/network-config-manager#147]
### Describe the bug

Hello,

When you execute: nmctl add-default-gateway eth3 gw 10.1.1.1

It should add in [Network] section the Gateway tag, instead it is added in [Route] section.

This cause default gateway loose if you then add some static route using 'add-route'.

Regards

### Reproduction steps

nmctl add-default-gateway eth3 gw 10.1.1.1

You will find in:
in /etc/systemd/network/<ifNet file>.network:
[Route]
Gateway=10.1.1.1

### Expected behavior

in /etc/systemd/network/<ifNet file>.network:
[Network]
Gateway=10.1.1.1

[Address]
Address=xxx.xxx.xxx.xxx/yy

**Comment by ufoonline** [comment]
I readed well the documentation [documentation](https://www.freedesktop.org/software/systemd/man/systemd.network.html#Gateway=) about and the current way to configure the default gateway is correct. 
But multiple '[Route]' section need to be managed as pointed-out for add-route on Issue 148.

**Comment by ssahani** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.network.html#Gateway=2 Yes . Hence closing this one
