### ISSUE TITLE
add-route replace previously added routes

### ISSUE THREAD

**Issue by ufoonline** [vmware/network-config-manager#148]
### Describe the bug

Hello,

If you execute multiple time "nmctl add-route" only last occurrence will be kept.

Regards

### Reproduction steps

1. nmctl add-route eth3 gw 10.100.10.2 dest 10.1.1.0/24
2. nmctl add-route eth3 gw 10.100.10.2 dest 10.1.2.0/24
3. nmctl add-route eth3 gw 10.100.10.5 dest 10.1.4.0/24

In /etc/system.d/network/10-eth3.network you will find only one occurrence of 'Route' section with the latest executed command.

### Expected behavior

 '/etc/system.d/network/10-eth3.network' should contain the following:
[Route]
Gateway=10.100.10.2
Destination=10.1.1.0/24

[Route]
Gateway=10.100.10.2
Destination=10.1.2.0/24

[Route]
Gateway=10.100.10.5
Destination=10.1.4.0/24

**Comment by ssahani** [comment]
Due to the underlying library multiple sections are not supported. Please use the https://github.com/vmware/network-config-manager#using-multiple-addresses-with-multiple-gateways-and-dhcp4 yaml format or https://github.com/vmware/pmd/tree/nxt

**Comment by ssahani** [comment]
Please test with latest code.

**Comment by ssahani** [comment]
Closing As multisection is now supported
