### ISSUE TITLE
Document set-ipv4 and set-ipv6

### ISSUE THREAD

**Issue by ssahani** [vmware/network-config-manager#677]
### Is your feature request related to a problem? Please describe.

set-ipv4 and set-ipv6 behaves diffrently with keep yes. We need to document it with other detail how it works

### Describe the solution you'd like

Document it

**Comment by ntsbtz** [comment]
Resolved - https://github.com/vmware/network-config-manager/pull/678/commits/a557f0093f63b1687246fba4129399f35852ce66

**Comment by ssahani** [comment]
We need to Document this too ```Fix: Adding support to tune accept-ra, dhcp and static address at once. Also setting address and gateway always overwrite existing ipv6 addresses and gateway without afecting ipv4 address and gateway.```
